version: 0.0
os: linux 
files: 
 - source: /index.html
   destination: /var/www/html
hooks:
  BeforeInstall:
   - location: deps
     timeout: 300
     runas: root
   - location: dep
     timeout: 300
     runas: root 